import { AgentConfig } from "@/lib/agentStore";

// Mock marketplace agents for demonstration
export const marketplaceAgents: (AgentConfig & {
  seller: string;
  sellerAvatar: string;
  rating: number;
  reviewCount: number;
  downloads: number;
  verified: boolean;
})[] = [
  {
    id: "mp-1",
    name: "Amazon KDP Publisher",
    role: "Amazon KDP platformasida kitob nashr qilish jarayonini to'liq avtomatlashtiradi: kalit so'z tahlili, sarlavha yaratish, tavsif yozish",
    tools: ["ai-brain", "web-search", "http-request"],
    status: "published",
    createdAt: "2025-02-15",
    price: 29,
    category: "E-Commerce",
    keywords: ["amazon", "kdp", "kitob", "publishing", "self-publish"],
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    apiCostPerMonth: 12.5,
    apiRequestsPerMonth: 4500,
    totalSales: 142,
    totalViews: 3200,
    reviews: { rating: 4.7, count: 89 },
    description: "Amazon KDP uchun to'liq avtomatlashtirilgan agent. Kalit so'z tahlili, raqobatchi tahlili, kitob sarlavhasi va tavsifini AI yordamida yaratadi. Oyiga 4500+ API so'rov bilan ishonchli va tez ishlaydi.",
    seller: "AIBooks Pro",
    sellerAvatar: "AB",
    rating: 4.7,
    reviewCount: 89,
    downloads: 142,
    verified: true,
  },
  {
    id: "mp-2",
    name: "SEO Content Master",
    role: "SEO optimallashtirilgan blog postlar, meta taglar va kontent strategiyasini avtomatik yaratadi",
    tools: ["ai-brain", "web-search", "file-analysis"],
    status: "published",
    createdAt: "2025-01-20",
    price: 19,
    category: "Marketing",
    keywords: ["seo", "kontent", "blog", "marketing", "traffic"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    apiCostPerMonth: 8.3,
    apiRequestsPerMonth: 3200,
    totalSales: 234,
    totalViews: 5100,
    reviews: { rating: 4.5, count: 156 },
    description: "SEO kontent yaratishni to'liq avtomatlashtiradigan agent. Google'da yuqori o'rinlarni egallash uchun kalit so'z tahlili, kontent rejasi va blog post yozish imkoniyatlarini taqdim etadi.",
    seller: "ContentFlow",
    sellerAvatar: "CF",
    rating: 4.5,
    reviewCount: 156,
    downloads: 234,
    verified: true,
  },
  {
    id: "mp-3",
    name: "Social Media Autopilot",
    role: "Instagram, Twitter va LinkedIn uchun kontent yaratadi, jadval tuzadi va analitika beradi",
    tools: ["ai-brain", "social-search", "http-request"],
    status: "published",
    createdAt: "2025-02-01",
    price: 15,
    category: "Marketing",
    keywords: ["instagram", "twitter", "linkedin", "social media", "post"],
    images: ["/placeholder.svg"],
    apiCostPerMonth: 6.7,
    apiRequestsPerMonth: 2800,
    totalSales: 89,
    totalViews: 2100,
    reviews: { rating: 4.2, count: 45 },
    description: "Ijtimoiy tarmoqlar uchun kontent yaratish va jadvallashtirishni avtomatlashtiruvchi agent.",
    seller: "SocialBot",
    sellerAvatar: "SB",
    rating: 4.2,
    reviewCount: 45,
    downloads: 89,
    verified: false,
  },
  {
    id: "mp-4",
    name: "Data Analyst Pro",
    role: "Ma'lumotlarni tahlil qiladi, vizualizatsiya yaratadi va biznes insaytlar beradi",
    tools: ["ai-brain", "database", "file-analysis", "code-execution"],
    status: "published",
    createdAt: "2025-03-01",
    price: 39,
    category: "Data",
    keywords: ["data", "analytics", "tahlil", "biznes", "hisobot"],
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    apiCostPerMonth: 15.8,
    apiRequestsPerMonth: 6200,
    totalSales: 67,
    totalViews: 1800,
    reviews: { rating: 4.8, count: 34 },
    description: "Kuchli data tahlil agenti. CSV, Excel fayllarini qayta ishlaydi, SQL so'rovlarni bajaradi va vizual hisobotlar tayyorlaydi.",
    seller: "DataWiz",
    sellerAvatar: "DW",
    rating: 4.8,
    reviewCount: 34,
    downloads: 67,
    verified: true,
  },
  {
    id: "mp-5",
    name: "Customer Support 24/7",
    role: "Mijozlar savollariga 24/7 javob beradi, FAQ boshqaradi va murakkab masalalarni eskalatsiya qiladi",
    tools: ["ai-brain", "database", "web-search"],
    status: "published",
    createdAt: "2025-01-10",
    price: 25,
    category: "Support",
    keywords: ["support", "mijoz", "xizmat", "bot", "faq"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    apiCostPerMonth: 9.4,
    apiRequestsPerMonth: 5100,
    totalSales: 312,
    totalViews: 7400,
    reviews: { rating: 4.6, count: 201 },
    description: "Mijozlarni qo'llab-quvvatlash uchun eng mashhur agent. 24/7 ishlaydi, ko'p tilli, va murakkab masalalarni inson operatorga uzatadi.",
    seller: "HelpDesk AI",
    sellerAvatar: "HD",
    rating: 4.6,
    reviewCount: 201,
    downloads: 312,
    verified: true,
  },
  {
    id: "mp-6",
    name: "Email Marketing Agent",
    role: "Email kampaniyalarni yaratadi, A/B test qiladi va konversiya analitikasini beradi",
    tools: ["ai-brain", "http-request", "file-analysis"],
    status: "published",
    createdAt: "2025-02-20",
    price: 12,
    category: "Marketing",
    keywords: ["email", "marketing", "kampaniya", "newsletter", "konversiya"],
    images: ["/placeholder.svg"],
    apiCostPerMonth: 5.2,
    apiRequestsPerMonth: 1900,
    totalSales: 178,
    totalViews: 3600,
    reviews: { rating: 4.3, count: 112 },
    description: "Email marketing kampaniyalarini yaratish va boshqarish uchun agent. A/B test, segmentatsiya va analitika imkoniyatlari.",
    seller: "MailFlow",
    sellerAvatar: "MF",
    rating: 4.3,
    reviewCount: 112,
    downloads: 178,
    verified: true,
  },
  {
    id: "mp-7",
    name: "Code Review Bot",
    role: "Kodni tekshiradi, xatolarni topadi, optimizatsiya takliflarini beradi va standartlarga muvofiqligini tekshiradi",
    tools: ["ai-brain", "code-execution"],
    status: "published",
    createdAt: "2025-03-05",
    price: 35,
    category: "Development",
    keywords: ["code", "review", "debug", "dasturlash", "optimizatsiya"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    apiCostPerMonth: 11.0,
    apiRequestsPerMonth: 3800,
    totalSales: 56,
    totalViews: 1500,
    reviews: { rating: 4.9, count: 28 },
    description: "Professional darajadagi kod review agenti. TypeScript, Python, Go va boshqa tillarda ishlaydi.",
    seller: "DevTools AI",
    sellerAvatar: "DT",
    rating: 4.9,
    reviewCount: 28,
    downloads: 56,
    verified: true,
  },
  {
    id: "mp-8",
    name: "Telegram Channel Manager",
    role: "Telegram kanalni boshqaradi: kontent yaratadi, jadval tuzadi, obunachilarga javob beradi",
    tools: ["ai-brain", "web-search", "http-request"],
    status: "published",
    createdAt: "2025-02-28",
    price: 10,
    category: "Marketing",
    keywords: ["telegram", "kanal", "bot", "kontent", "obuna"],
    images: ["/placeholder.svg"],
    apiCostPerMonth: 4.1,
    apiRequestsPerMonth: 1500,
    totalSales: 423,
    totalViews: 8900,
    reviews: { rating: 4.4, count: 267 },
    description: "Telegram kanal va guruhlarni boshqarish uchun eng arzon va samarali agent.",
    seller: "TG Master",
    sellerAvatar: "TG",
    rating: 4.4,
    reviewCount: 267,
    downloads: 423,
    verified: false,
  },
];

export const CATEGORIES = [
  "Barchasi",
  "E-Commerce",
  "Marketing",
  "Data",
  "Support",
  "Development",
  "Research",
  "SEO",
  "Content",
  "General",
];

export const SORT_OPTIONS = [
  { value: "popular", label: "Mashhurlik" },
  { value: "newest", label: "Eng yangi" },
  { value: "price-low", label: "Narx: past → yuqori" },
  { value: "price-high", label: "Narx: yuqori → past" },
  { value: "rating", label: "Reyting" },
];
